apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-secret.yaml
  - 01-postgres-pvc.yaml
  - 02-postgres.yaml
  - 03-prisma-job.yaml
  - 04-backend.yaml
  - 05-frontend.yaml
  - 06-certificate.yaml
  - 07-ingress.yaml